--VYVTOŘENÍ SPOJENÉ TABULKY, DOPOČÍTÁNÍ CENY ZA POČET KUSŮ V ČÁSTECH OBJEDNÁVKY
CREATE OR REPLACE TEMPORARY TABLE JOINED_DATA_PRODEJE AS
SELECT DP.*, P.CATEGORY, (P.PRICE * DP.QUANTITY) AS PRICE_QUANTITY
FROM DATA_PRODEJE AS DP
LEFT JOIN PRODUCTS AS P
ON DP.PRODUCT_NAME = P.PRODUCT_NAME
;

--PŘETYPOVÁNÍ SLOUPCE DATE NA FORMÁT DATUM

CREATE OR REPLACE TEMPORARY TABLE JOINED_DATA_PRODEJE AS
SELECT TRANSACTION_ID,  
       TO_DATE(DATE, 'DD.MM.YYYY') AS DATE, 
       PRODUCT_NAME, QUANTITY, CATEGORY, PRICE_QUANTITY
FROM JOINED_DATA_PRODEJE;

--1.	Na jaké kategorii produktů máme největší obrat? A zajímalo by mě i jestli se to v jednotlivých měsících mění.
-- OBRAT ZA CELKOVÉ OBDOBÍ PODLE KATEGORIÍ
SELECT CATEGORY, SUM(PRICE_QUANTITY) AS OBRAT
FROM JOINED_DATA_PRODEJE
GROUP BY CATEGORY 
ORDER BY OBRAT DESC
LIMIT 1
;

-- POHLED PO MĚSÍCÍCH 
SELECT CATEGORY,DATE_TRUNC('MONTH', DATE) AS MESIC, 
       SUM(PRICE_QUANTITY) AS CELKOVY_OBAR_MESIC
FROM JOINED_DATA_PRODEJE
GROUP BY MESIC, CATEGORY
ORDER BY MESIC,CELKOVY_OBAR_MESIC DESC;

--V KAŽDÉM MĚSÍCI UKÁŽE JEN NEJZASTOUPENĚJŠÍ KATEGORII
SELECT CATEGORY, 
       DATE_TRUNC('MONTH', DATE) AS MESIC, 
       SUM(PRICE_QUANTITY) AS CELKOVY_OBRAT_MESIC
FROM JOINED_DATA_PRODEJE
GROUP BY MESIC, CATEGORY
QUALIFY ROW_NUMBER() OVER (PARTITION BY MESIC ORDER BY SUM(PRICE_QUANTITY) DESC) = 1;

--2.	Který den v týdnu je nejsilnější na počet objednávek?
--DNY V TYDNU
ALTER TABLE JOINED_DATA_PRODEJE
ADD COLUMN DAY_NAME STRING;

UPDATE JOINED_DATA_PRODEJE
SET day_name = TO_CHAR(DATE, 'DY');

SELECT DAY_NAME, COUNT (DISTINCT TRANSACTION_ID) AS POCET_OBJEDNAVEK
FROM JOINED_DATA_PRODEJE
GROUP BY DAY_NAME
ORDER BY POCET_OBJEDNAVEK DESC
LIMIT 1
;
